### ISSUE TITLE
Implement the relation between Locations and Lines so that available stations from one location are accessible

### ISSUE THREAD

**Issue by dombosfi** [sopra-fs21-group-08/sopra-fs21-group08-server#59]
time estimate: 6h

This task is part of User stories: #18 

EDIT: changed time estimate

**Comment by maximilianhuwyler** [comment]
78a6a32af8a725ac22e36393a927be58770b4e8c

**Comment by dombosfi** [comment]
We descided to have Locations related to their neighbouring Locations
